// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phlifyyekjcdktqtkmyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobGlmeXlla2pjZGt0cXRrbXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzczNDIsImV4cCI6MjA1NTgxMzM0Mn0.GO-4I6cbuGllAqoVcQ5WlRTu-SErYOXLleajvmxoXK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);